accounts/urls.py
from django.urls import path
from .views import logout_view, signup, login_view

app_name = "accounts"

urlpatterns = [
    path("logout/", logout_view, name="logout"),
    path("signup/", signup, name="signup"),
    path("login/", login_view, name="login"),
]

projects/urls.py
from django.urls import path, include
from . import views

app_name = "projects"

urlpatterns = [
    path("", views.list_projects, name="list_projects"),
    path("<int:id>/", views.show_project, name="show_project"),
    path("create/", views.create_project, name="create_project"),
    path("tasks/", include("tasks.urls"), name="tasks"),
]

tasks/urls.py
from django.urls import path
from .views import create_task
from .views import ShowMyTasksView

app_name = "task"

urlpatterns = [
    path("create/", create_task, name="create_task"),
    path("mine/", ShowMyTasksView.as_view(), name="show_my_tasks"),
]

tracker/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from accounts.views import login_view, signup
from tasks.views import create_task

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls", namespace="projects")),
    path("", lambda request: redirect("projects:list_projects"), name="home"),
    path("accounts/login/", login_view, name="login"),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/signup/", signup, name="signup"),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("tasks/create/", create_task, name="create_task"),
]

accounts/models.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput())

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        User, related_name="projects", on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return self.name


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description", "owner"]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Project


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        User, related_name="tasks", on_delete=models.CASCADE, null=True
    )

accounts/forms.py
from django import forms


class SignupForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)
    password_confirmation = forms.CharField(
        max_length=150, widget=forms.PasswordInput
    )


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput())

accounts/forms/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)

projects/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description", "owner"]

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["name", "start_date", "due_date", "assignee", "project"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .forms import LoginForm, SignupForm


def logout_view(request):
    logout(request)
    return redirect("login")


def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")
    else:
        form = LoginForm()
    return render(request, "accounts/login.html", {"form": form})


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            password_confirmation = form.cleaned_data.get(
                "password_confirmation"
            )
            if password != password_confirmation:
                return render(
                    request,
                    "accounts/signup.html",
                    {"form": form, "error": "the passwords do not match"},
                )
            user = User.objects.create_user(
                username=username, password=password
            )
            if user is not None:
                login(request, user)
                return redirect("list_projects")
            else:
                return render(
                    request,
                    "accounts/signup.html",
                    {"form": form, "error": "the passwords do not match"},
                )
    else:
        form = SignupForm()
    return render(request, "accounts/signup.html", {"form": form})

projects/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Project
from .forms import ProjectForm


@login_required
def list_projects(request):
    if request.user.is_authenticated:
        projects = Project.objects.filter(owner=request.user)
        context = {"projects": projects}
        return render(request, "projects/list_projects.html", context)
    else:
        return redirect("login")


@login_required
def show_project(request, id):
    project = Project.objects.get(id=id)
    context = {"project": project}
    return render(request, "projects/show_project.html", context)


def create_project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("list_projects")
    else:
        form = ProjectForm()
    return render(request, "projects/create_project.html", {"form": form})

tasks/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import TaskForm
from .models import Task
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView


@login_required
def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("projects:list_projects")
    else:
        form = TaskForm()
    return render(request, "tasks/create.html", {"form": form})


class ShowMyTasksView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/show_my_tasks.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'task:show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'projects:list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>Login</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Login</button>
                </form>
            </div>
        </main>
    </body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Signup</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'task:show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'projects:list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>Signup</h1>
                {% if error %}<p>{{ error }}</p>{% endif %}
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Signup</button>
                </form>
            </div>
        </main>
    </body>
</html>

projects/templates/projects/create_project.html
<!DOCTYPE html>
<html>
    <head>
        <title>Create a new project</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'task:show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'projects:list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>Create a new project</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

projects/templates/projects/list_projects.html
<!DOCTYPE html>
<html>
    <head>
        <title>My Projects</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'task:show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'projects:list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>My Projects</h1>
                <p>
                    <a href="{% url 'create_project' %}">Create a new project</a>
                </p>
                {% if projects %}
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Number of tasks</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for project in projects %}
                                <tr>
                                    <td>
                                        <a href="{% url 'show_project' project.id %}">{{ project.name }}</a>
                                    </td>
                                    <td>{{ project.tasks.all|length }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>You are not assigned to any projects</p>
                {% endif %}
            </div>
        </main>
    </body>
</html>

projects/templates/projects/show_project.html
<!DOCTYPE html>
<html>
    <head>
        <title>Project Details</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'task:show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'projects:list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>{{ project.name }}</h1>
                <p>{{ project.description }}</p>
                <h2>Tasks</h2>
                <p>
                    <a href="{% url 'tasks:create_task' %}">Create a new task</a>
                </p>
                {% if project.tasks.all %}
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Assignee</th>
                                <th>Start date</th>
                                <th>Due date</th>
                                <th>Is completed</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for task in project.tasks.all %}
                                <tr>
                                    <td>{{ task.name }}</td>
                                    <td>{{ task.assignee.username }}</td>
                                    <td>{{ task.start_date }}</td>
                                    <td>{{ task.due_date }}</td>
                                    <td>{{ task.is_completed|yesno }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>This project has no tasks</p>
                {% endif %}
            </div>
        </main>
        <footer>
            {# footer content #}
        </footer>
    </body>
</html>

tasks/templates/tasks/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Create Task</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'task:show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'projects:list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <nav>
            <!-- navigation links here -->
        </nav>
        <main>
            <div>
                <h1>Create a new task</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Create</button>
                </form>
            </div>
        </main>
        <aside>
            <!-- additional content here -->
        </aside>
        <footer>
            <!-- footer content here -->
        </footer>
    </body>
</html>

tasks/templates/tasks/show_my_tasks.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'task:show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'projects:list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>My Tasks</h1>
                {% if object_list %}
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Start date</th>
                                <th>Due date</th>
                                <th>Is completed</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for task in object_list %}
                                <tr>
                                    <td>{{ task.name }}</td>
                                    <td>{{ task.start_date }}</td>
                                    <td>{{ task.due_date }}</td>
                                    <td>{{ task.is_completed|yesno:"yes,no" }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>You have no tasks</p>
                {% endif %}
            </div>
        </main>
    </body>
</html>